### ISSUE TITLE
java.lang.IllegalAccessError:

### ISSUE THREAD

**Issue by desmondkr** [MatthiasKerat/BLETutorialYt#4]
Hello when i download the repositiory and try to run it, i get following error message:

```
java.lang.IllegalAccessError: class org.jetbrains.kotlin.kapt3.base.KaptContext (in unnamed module @0x71968c3d) cannot access class com.sun.tools.javac.util.Context (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.util to unnamed module @0x71968c3d
	at org.jetbrains.kotlin.kapt3.base.KaptContext.<init>(KaptContext.kt:28)
	at org.jetbrains.kotlin.kapt3.KaptContextForStubGeneration.<init>(KaptContextForStubGeneration.kt:40)
	at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.contextForStubGeneration(Kapt3Extension.kt:287)
	at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.analysisCompleted(Kapt3Extension.kt:171)
	at org.jetbrains.kotlin.kapt3.ClasspathBasedKapt3Extension.analysisCompleted(Kapt3Extension.kt:102)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$invokeExtensionsOnAnalysisComplete(TopDownAnalyzerFacadeForJVM.kt:112)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:122)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:86)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:252)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:243)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:113)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:243)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:90)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:56)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:169)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:92)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:412)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:112)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally(IncrementalCompilerRunner.kt:358)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally$default(IncrementalCompilerRunner.kt:300)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl$rebuild(IncrementalCompilerRunner.kt:119)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:170)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:81)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:607)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:96)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1658)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

I have tried to change the jdk but that didnt resolve the error. Has anyone encountered this before or knows how to resolve it?

**Comment by qccongqin** [comment]
@desmondkr  try clean cache and reboot AndroidStudio.

**Comment by Melus144** [comment]
It worked for you? What JDK version are you using? I got the same issue,

**Comment by 1Shrinivas** [comment]
I'm also getting Same issue? I changed JDK version 8 to JDK 17 ?i got same issue, Can anyone tell how to solve this ,
2024-03-07 12:39:47.877 14563-15677 BlockableFutures        usap64                               E  Cannot block on non-blocking thread
                                                                                                    java.lang.IllegalStateException: Cannot block on non-blocking thread: BG Thread #7
                                                                                                    	at cmhf.c(PG:11)
                                                                                                    	at cmhf.a(PG:1)
                                                                                                    	at bafq.call(PG:350)
                                                                                                    	at android.content.ContentProvider.call(ContentProvider.java:2548)
                                                                                                    	at baec.call(PG:2)
                                                                                                    	at android.content.ContentProvider$Transport.call(ContentProvider.java:538)
                                                                                                    	at android.content.ContentResolver.call(ContentResolver.java:2494)
                                                                                                    	at android.content.ContentResolver.call(ContentResolver.java:2474)
                                                                                                    	at cgee.f(PG:6)
                                                                                                    	at cgee.d(PG:1)
                                                                                                    	at cgdd.a(PG:1)
                                                                                                    	at ccxr.al(PG:9)
                                                                                                    	at ccxr.ak(PG:8)
                                                                                                    	at ccxr.a(PG:1)
                                                                                                    	at cepm.o(PG:4)
                                                                                                    	at cepm.k(PG:4)
                                                                                                    	at cepm.c(PG:1)
                                                                                                    	at cdvf.b(PG:1)
                                                                                                    	at ccto.C(PG:12)
                                                                                                    	at ccus.i(PG:1)
                                                                                                    	at ccus.h(PG:7)
                                                                                                    	at cedo.j(PG:2)
                                                                                                    	at cedo.b(PG:27)
                                                                                                    	at bpzv.run(PG:1)
                                                                                                    	at dess.run(PG:1)
                                                                                                    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
                                                                                                    	at dkvh.a(PG:1)
                                                                                                    	at dkud.run(PG:4)
                                                                                                    	at dkvi.run(PG:1)
                                                                                                    	at cmfn.run(PG:1)
                                                                                                    	at dhps.run(PG:23)
                                                                                                    	at cmik.run(PG:3)
                                                                                                    	at cmeo.run(PG:2)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    	at cmfq.run(PG:6)
2024-03-07 12:39:47.879 14563-15677 BlockableFutures        usap64                               E  Cannot block on non-blocking thread
                                                                                                    java.lang.IllegalStateException: Cannot block on non-blocking thread: BG Thread #7
                                                                                                    	at cmhf.c(PG:11)
                                                                                                    	at cmhf.a(PG:1)
                                                                                                    	at bafq.call(PG:350)
                                                                                                    	at android.content.ContentProvider.call(ContentProvider.java:2548)
                                                                                                    	at baec.call(PG:2)
                                                                                                    	at android.content.ContentProvider$Transport.call(ContentProvider.java:538)
                                                                                                    	at android.content.ContentResolver.call(ContentResolver.java:2494)
                                                                                                    	at android.content.ContentResolver.call(ContentResolver.java:2474)
                                                                                                    	at cgee.f(PG:6)
                                                                                                    	at cgee.d(PG:1)
                                                                                                    	at cgdd.a(PG:1)
                                                                                                    	at ccxr.al(PG:9)
                                                                                                    	at ccxr.ak(PG:8)
                                                                                                    	at ccxr.a(PG:1)
                                                                                                    	at cepm.k(PG:12)
                                                                                                    	at cepm.c(PG:1)
                                                                                                    	at cdvf.b(PG:1)
                                                                                                    	at ccto.C(PG:12)
                                                                                                    	at ccus.i(PG:1)
                                                                                                    	at ccus.h(PG:7)
                                                                                                    	at cedo.j(PG:2)
                                                                                                    	at cedo.b(PG:27)
                                                                                                    	at bpzv.run(PG:1)
                                                                                                    	at dess.run(PG:1)
                                                                                                    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
                                                                                                    	at dkvh.a(PG:1)
                                                                                                    	at dkud.run(PG:4)
                                                                                                    	at dkvi.run(PG:1)
                                                                                                    	at cmfn.run(PG:1)
                                                                                                    	at dhps.run(PG:23)
                                                                                                    	at cmik.run(PG:3)
                                                                                                    	at cmeo.run(PG:2)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    	at cmfq.run(PG:6)
2024-03-07 12:39:49.202 10777-10777 ion                     com.truecaller                       E  ioctl c0044901 failed with code -1: Invalid argument
2024-03-07 12:39:49.213 10777-10777 RippleDrawable          com.truecaller                       E  The RippleDrawable.STYLE_PATTERNED animation is not supported for a non-hardware accelerated Canvas. Skipping animation.
2024-03-07 12:39:50.391  1621-1983  OplusThermalServic
